In [459]:
import numpy as np

In [460]:
np.zeros(3)

array([0., 0., 0.])

In [461]:
np.zeros((12,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [462]:
type(np.zeros((12,12)))

numpy.ndarray

In [463]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [464]:
p = np.ones((5,5))

In [465]:
p + 4 **2

array([[17., 17., 17., 17., 17.],
       [17., 17., 17., 17., 17.],
       [17., 17., 17., 17., 17.],
       [17., 17., 17., 17., 17.],
       [17., 17., 17., 17., 17.]])

In [466]:
a = np.linspace(1,100,10)
b = a
c = a / b

In [467]:
a = np.ones((5,5))

In [468]:
print("LEN IS = " + str(len(a)) +" SHAPE IS = " + str(np.shape(a)) )

LEN IS = 5 SHAPE IS = (5, 5)


In [469]:
#Identity matrix addition
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.eye(3)
type(x)
type(y)
x + 1
y + 1

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

### _**Python Array**_ means _Numpy Array_. Python _Lists_ are not like Numpy Arrays. Also, Numpy has Matrix type data.

#### What are the differences between numpy arrays and matrices? Which one should I use?

* Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. Matrix objects are a subclass of ndarray, so they inherit all the attributes and methods of ndarrays.
* The main advantage of numpy matrices is that they provide a convenient notation for matrix multiplication: if a and b are matrices, then a*b is their matrix product.

In [470]:
import numpy as np

a=np.mat('4 3; 2 1')
b=np.mat('1 2; 3 4')
print(a)
# [[4 3]
#  [2 1]]
print(b)
# [[1 2]
#  [3 4]]
print(a*b)
# [[13 20]
#  [ 5  8]]

[[4 3]
 [2 1]]
[[1 2]
 [3 4]]
[[13 20]
 [ 5  8]]


In [471]:
np.random.rand(5)

array([0.38659638, 0.46212547, 0.57862899, 0.1139206 , 0.36841365])

In [472]:
#random number with normal distribution
np.random.randn(12)

array([ 0.86340647, -0.31638123, -0.90222577, -0.73856239, -0.39533888,
        0.08420085, -0.18562245,  1.10843923,  1.29821024,  0.24722299,
        0.26166457, -0.53374215])

In [473]:
np.random.normal(loc=100,scale=12,size=20)

array([ 97.89619737,  99.50115019,  98.92939605,  92.59587993,
       124.63424835, 108.86873747, 117.07258467,  96.46901945,
       112.54938927, 111.63855716, 120.93340411,  99.71115055,
       101.99228492, 112.45714111,  87.3033251 , 117.41036149,
        93.04140442, 130.2870838 ,  80.85568945,  96.2547928 ])

In [474]:
mean, sigma, size = 0, 0.1, 10 # mean and standard deviation
np.random.normal(mean,sigma,size)

array([-0.02971083,  0.14325602,  0.08962765,  0.05586588,  0.04757455,
       -0.01348464, -0.00597695,  0.03889121,  0.20951921, -0.00259634])

In [475]:
#random number between integrers
a = np.random.randint(1,10)
b = np.random.randint(1,10,10)

In [476]:
a

6

In [477]:
b

array([1, 1, 6, 2, 4, 3, 4, 2, 1, 7])

In [478]:
#setting up seed
np.random.seed(100) #Seed must be between 0 and 2**32 - 1
np.random.rand(4)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613])

### How to populate random array and reshape into 2x2 array

In [479]:
random_array = np.random.randint(0,100,100)

In [480]:
random_array

array([94, 52, 98, 53, 66, 98, 14, 34, 24, 15, 60, 58, 16,  9, 93, 86,  2,
       27,  4, 31,  1, 13, 83,  4, 91, 59, 67,  7, 49, 47, 65, 61, 14, 55,
       71, 80,  2, 94, 19, 98, 63, 53, 27, 56, 30, 48, 47, 39, 38, 44, 18,
       64, 56, 34, 53, 74, 17, 72, 13, 30, 17, 53, 68, 50, 91, 91, 83, 53,
       78,  0, 13, 57, 76,  3, 70,  3, 84, 79, 10, 87, 60,  3, 48, 52, 43,
       36,  5, 71, 38, 86, 94, 98, 42, 84, 95, 76, 33, 58, 42, 22])

In [481]:
random_array.reshape(10,10)

array([[94, 52, 98, 53, 66, 98, 14, 34, 24, 15],
       [60, 58, 16,  9, 93, 86,  2, 27,  4, 31],
       [ 1, 13, 83,  4, 91, 59, 67,  7, 49, 47],
       [65, 61, 14, 55, 71, 80,  2, 94, 19, 98],
       [63, 53, 27, 56, 30, 48, 47, 39, 38, 44],
       [18, 64, 56, 34, 53, 74, 17, 72, 13, 30],
       [17, 53, 68, 50, 91, 91, 83, 53, 78,  0],
       [13, 57, 76,  3, 70,  3, 84, 79, 10, 87],
       [60,  3, 48, 52, 43, 36,  5, 71, 38, 86],
       [94, 98, 42, 84, 95, 76, 33, 58, 42, 22]])

In [482]:
# random_array.reshape(12,10) # Reshape fails because dimension is unable to reshape

In [483]:
print(str(random_array.max()) + " is the largest number at index "+ str(random_array.argmax()))

98 is the largest number at index 2


In [484]:
print(str(random_array.min()) + " is the smallest number at index "+ str(random_array.argmin()))

0 is the smallest number at index 69


In [485]:
random_array.dtype

dtype('int32')

### Numpy Indexing and Selection

In [486]:
myarray = np.arange(0,20)

In [487]:
myarray[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [488]:
myarray[:5]

array([0, 1, 2, 3, 4])

In [489]:
myarray / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [490]:
myarray ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [491]:
slice_ = myarray [0:5]

In [492]:
slice_

array([0, 1, 2, 3, 4])

In [493]:
slice_[:] = slice_ * 10

In [494]:
slice_[:] = 99

In [495]:
slice_

array([99, 99, 99, 99, 99])

In [496]:
myarray

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [497]:
#creating copy of array
ma = myarray.copy()
ma

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Populate random array and convert to matrix 

In [498]:
arr_2d = np.random.rand(9) * 10
arr_2d = arr_2d.reshape(3,3)
arr_2d.shape
arr_2d[1]

array([2.04345277, 2.76765061, 2.46535881])

In [499]:
#Slicing 2d array
arr_2d[:2]
arr_2d[:2,]

array([[6.02296658, 3.8776628 , 3.63188004],
       [2.04345277, 2.76765061, 2.46535881]])

In [500]:
#slicing big array
#q = np.random.randint(1,9,100)
q = np.eye(10,10)
q = q.reshape(10,10)
q
#q.shape


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [501]:
q[5:8,4:-1] #get 5 by 5

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [502]:
#Conditional filtering
myarr = np.random.randint(-10,10,20)
myarr

array([-4, -5, -4, -3,  1,  9, -8,  9,  7,  3, -5,  3, -7,  6,  2,  8,  3,
        2, -7,  0])

In [503]:
myarr_nonzero = myarr[myarr > 0]
len(myarr_nonzero)
myarr_nonzero

array([1, 9, 9, 7, 3, 3, 6, 2, 8, 3, 2])

In [506]:
myarr[myarr == 2]
myarr[myarr <= -1]
myarr[myarr % 2 ==0 ]

array([-4, -4, -8,  6,  2,  8,  2,  0])

In [517]:
arr = np.linspace(start=10,stop=50,num=40)
arr

array([10.        , 11.02564103, 12.05128205, 13.07692308, 14.1025641 ,
       15.12820513, 16.15384615, 17.17948718, 18.20512821, 19.23076923,
       20.25641026, 21.28205128, 22.30769231, 23.33333333, 24.35897436,
       25.38461538, 26.41025641, 27.43589744, 28.46153846, 29.48717949,
       30.51282051, 31.53846154, 32.56410256, 33.58974359, 34.61538462,
       35.64102564, 36.66666667, 37.69230769, 38.71794872, 39.74358974,
       40.76923077, 41.79487179, 42.82051282, 43.84615385, 44.87179487,
       45.8974359 , 46.92307692, 47.94871795, 48.97435897, 50.        ])